remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-remote-theme

title:                 Starter Kit

description:           >
  Hydejack is a boutique Jekyll theme for hackers, nerds, and academics,
  with a focus on personal sites that are meant to impress.

logo:                  /assets/img/logo.png
