remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-remote-theme

title:                 Boids Algorithm
description:           >
  This is our webpage on the Boids algorithm

logo:                  /birdlogo.jpg

menu:
  - title:             Explanation
    url:               /explanation
  - title:             Showcase
    url:               /showcase
  - title:             Analysis
    url:               /analysis
  - title:             Journal
    url:               /journal
  - title:             Download
    url:               /download

# Sidebar image and theme color of the site.
accent_image:          /birdflock.jpg
accent_color:          rgb(79,177,186)

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com
