remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-remote-theme

title:                 Boids Algorithm
url: "https://are-dynamic-2025-g6.github.io/boids/website/"
description:           >
  ARE - Research Project - By Loueï Muller, Gavriel Myara, Liron Afriat, Luka Arnaud, and Bastien Thieulot

logo:                  website/birdlogo_resized.jpg

author:
  name:                Loueï Muller
  email:               yurkiyurki1@gmail.com

copyright:             © 2025


menu:
  - title:             Explication
    url:               website/explication
  - title:             Showcase
    url:               website/showcase
  - title:             Analyse
    url:               website/analyse
  - title:             Choix
    url:               website/choix
  - title:             Conclusion
    url:               website/conclusion
  - title:             Download
    url:               website/download

# Sidebar image and theme color of the site.
accent_image:          website/birdflock.jpg
accent_color:          rgb(255, 215, 0)

hydejack:
  dark_mode:
    dynamic: true
    icon:    true
    always:  false

